# Zadanie domowe #6 - Radosław Cacała

## Zadanie #1

In [13]:
import numpy as np

# 1)
a = np.arange(0.0, 1.1, 0.1)   # shape (11,)

# 2)
b = np.zeros((5, 6), dtype=np.int8)

# 3)
x = complex(0, 1)
c = np.array([x**k for k in range(9)])  # shape (9,)

print(a)
print(b)
print(c)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[ 1.+0.j  0.+1.j -1.+0.j -0.-1.j  1.+0.j  0.+1.j -1.+0.j -0.-1.j  1.+0.j]


## Zadanie #2

In [14]:
v1 = np.array([10, 20, 30, 40, 50, 60, 70])

v2 = v1[1::2]
#numerowanie od zera
v3 = v1[::-1]

print(v2)
print(v3)

[20 40 60]
[70 60 50 40 30 20 10]


## Zadanie #3

In [15]:
m1 = np.arange(20).reshape(4, 5)

m2 = m1[:, ::-1]

m3 = m1[::-1, :]

m4 = m1[1:-1, 1:-1]

print(m1)
print(m2)
print(m3)
print(m4)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 10]
 [19 18 17 16 15]]
[[15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]
[[ 6  7  8]
 [11 12 13]]
